---
title: "Other Populations"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r Cluster11}
library(Seurat)

CAM <- subset(clusters, ident = 11)

p1 <- FeaturePlot(CAM, features = c('Cd74', 'H2-Aa'), blend =  TRUE)
FeaturePlot(CAM, features = c('Cd36', 'Clec4n'), blend = TRUE)
p2 <- FeaturePlot(CAM, features = c('Lilra5', 'H2-Eb1'), blend =  TRUE)
FeaturePlot(CAM, features = 'Lilra5')
FeaturePlot(CAM, features = 'H2-Aa')
FeaturePlot(CAM, features = c('Mrc1', 'Pf4'), blend = TRUE)

FeaturePlot(CAM, features = 'Clec4n')
FeaturePlot(CAM, features = 'Fkbp5')
FeaturePlot(CAM, features = 'Cd36')


write.csv(cluster11, file = '/Users/sanachintamen/Desktop/cluster11_GO.csv')


```
```{r Cluster6_IEG}


IEG <- subset(clusters, ident = 6)
FeaturePlot(IEG, features = c('Fos','Egr1'), blend = TRUE)
FeaturePlot(IEG, features = c('Btg2','Jun'), blend = TRUE)


DotPlot(IEG, features = c('Fos','Egr1','Jun','Junb','Dusp1','Btg2', 'Zfp36' ))

```



```{r}

IFN <- subset(clusters, ident = 7)
FeaturePlot(IFN, features = c('Fcgr1','Ly6e'), blend = TRUE)
FeaturePlot(IFN, features = c('Oasl2','Ifitm3'), blend = TRUE)

FeaturePlot(IFN, features = c('Oasl2'))
FeaturePlot(IFN, features = c('Ifitm3'))



write.csv(cluster7, file = '/Users/sanachintamen/Desktop/cluster7_GO.csv')

```
```{r Proliferating}

Prol <- subset(clusters, ident = 13)

FeaturePlot(Prol, features = c('Mki67', 'Top2a'), blend = TRUE)
FeaturePlot(Prol, features = c('Stmn1', 'H2afz'), blend = TRUE)
FeaturePlot(Prol, features = c('Mki67', 'Top2a'), blend = TRUE)
FeaturePlot(Prol, features = c('Rbbp7', 'Ppia'), blend = TRUE)
Stmn1
FeaturePlot(IFN, features = c('Oasl2'))
```

