---
title: "R Notebook"
output: html_notebook
---



```{r libraries}
library(Seurat)
library(sctransform)
library(tidyr)
library(gdata)
library(ggplot2)
```


```{r SS01}

matrix_dir = '/Volumes/Critical\ Care/Kernie\ Lab/Sana/Single\ Cell\ Project/Run1/internal_files/raw_feature_bc_matrix/'
MG <- Read10X(data.dir = matrix_dir)
MG <- CreateSeuratObject(counts= MG, project = 'SS01')
MG[["percent.mt"]] <- PercentageFeatureSet(MG, pattern = "^mt-")
MG <- subset(MG, subset = nFeature_RNA > 1000 & nCount_RNA >2500 &percent.mt < 20)
MG <- SCTransform(MG, vars.to.regress = "percent.mt", verbose = FALSE)


saveRDS(MG, file = '/Users/sanachintamen/Desktop/SS01.Rds')

```

```{r SS02}
matrix_dir = '/Volumes/Critical\ Care/Kernie\ Lab/Sana/Single\ Cell\ Project/Run2\ /output/SS002/cellranger_analysis_outs/raw_feature_bc_matrix/'
MG <- Read10X(data.dir = matrix_dir)
MG <- CreateSeuratObject(counts= MG, project = 'SS02')
MG[["percent.mt"]] <- PercentageFeatureSet(MG, pattern = "^mt-")
MG <- subset(MG, subset = nFeature_RNA > 1000 & nCount_RNA >2500 &percent.mt < 20)
MG <- SCTransform(MG, vars.to.regress = "percent.mt", verbose = FALSE)


saveRDS(MG, file = '/Users/sanachintamen/Desktop/SS02.Rds')
```


```{r SS03}
matrix_dir = '/Volumes/Critical\ Care/Kernie\ Lab/Sana/Single\ Cell\ Project/Run3/cellranger_analysis_outs/raw_feature_bc_matrix/'
MG <- Read10X(data.dir = matrix_dir)
MG <- CreateSeuratObject(counts= MG, project = 'SS03')
MG[["percent.mt"]] <- PercentageFeatureSet(MG, pattern = "^mt-")
MG <- subset(MG, subset = nFeature_RNA > 1000 & nCount_RNA >2500 &percent.mt < 20)
MG <- SCTransform(MG, vars.to.regress = "percent.mt", verbose = FALSE)


saveRDS(MG, file = '/Users/sanachintamen/Desktop/SS03.Rds')
```

```{r List}
rm(list = ls())
MG_1 <- readRDS('/Users/sanachintamen/Desktop/SS01.Rds')
MG_2 <- readRDS('/Users/sanachintamen/Desktop/SS02.Rds')
MG_3 <- readRDS('/Users/sanachintamen/Desktop/SS03.Rds')

mg_list <- c(MG_1, MG_2, MG_3)
keep(mg_list, sure = TRUE)
```


```{r anchors}
features <- SelectIntegrationFeatures(object.list = mg_list, 
                                      nfeatures = 3000)
mg_list <- PrepSCTIntegration(object.list = mg_list, 
                              anchor.features = features)
anchors <- FindIntegrationAnchors(object.list = mg_list, 
                                  normalization.method = 'SCT', 
                                  anchor.features = features)

saveRDS(anchors, file = '/Users/sanachintamen/Desktop/cx3cr1_anchors.Rds')
```

```{r integration}
rm(mg_list, features)
samples.combined <- IntegrateData(anchorset= anchors, normalization.method = 'SCT')
```

```{r PCA}
samples.combined<- RunPCA(samples.combined, 
                          verbose = FALSE)
saveRDS(samples.combined, file = '/Users/sanachintamen/Desktop/cx3cr1_integrated.Rds')
ElbowPlot(samples.combined, ndims = 50)
```

```{r Clustering}
rm(anchors)
samples.combined <- RunUMAP(samples.combined, 
                            reduction = "pca", 
                            dims = 1:40)
clusters <- FindNeighbors(samples.combined, 
                          dims = 1:40)
clusters <- FindClusters(clusters, 
                         resolution = 0.5)

saveRDS(clusters, file = '/Users/sanachintamen/Desktop/Cx3cr1_clusters.Rds')
```



```{r DIMPLOTS}
library(Seurat)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
clusters <- readRDS(file = '/Users/sanachintamen/Desktop/Cx3cr1_clusters.Rds', refhook = NULL)

#Note: compile CTCN colors before running
DimPlot(clusters, label =TRUE) +CTCN_chroma("mixed7") + theme_void() + NoLegend()
```


```{r percentgraph}
library(dplyr)
library(paletteer)
library(tidyr)

meta <- clusters@meta.data
meta <- as.data.frame(meta)

run1 <- filter(meta, orig.ident == 'SS01')
run1 <- as.data.frame(table(run1$seurat_clusters))
run <- 'SS01'
length(run) <- 14
run <- replace_na(run, 'SS01')
run1 <- cbind(run, run1)
colnames(run1) <-c('RunID', 'ClusterID', 'CellCount')
totalcells <- sum(run1$CellCount)
Percent <- ((run1$CellCount)/totalcells) * 100
Percent <- round(Percent, digits=2)
run1 <- cbind(run1, Percent)


run2<- filter(meta, orig.ident == 'SS02')
run2 <- as.data.frame(table(run2$seurat_clusters))
run <- 'SS02'
length(run) <- 14
run <- replace_na(run, 'SS02')
run2 <- cbind(run, run2)
colnames(run2) <-c('RunID', 'ClusterID', 'CellCount')
totalcells <- sum(run2$CellCount)
Percent <- ((run2$CellCount)/totalcells) * 100
Percent <- round(Percent, digits=2)
run2 <- cbind(run2, Percent)


run3<- filter(meta, orig.ident == 'SS03')
run3 <- as.data.frame(table(run3$seurat_clusters))
run <- 'SS03'
length(run) <- 14
run <- replace_na(run, 'SS03')
run3 <- cbind(run, run3)
colnames(run3) <-c('RunID', 'ClusterID', 'CellCount')
totalcells <- sum(run3$CellCount)
Percent <- ((run3$CellCount)/totalcells) * 100
Percent <- round(Percent, digits=2)
run3 <- cbind(run3, Percent)

runs <- rbind(run1, run2, run3)
```


```{r percentgraphplot}
p <- ggplot(runs, aes(fill= ClusterID, y= Percent, x= RunID)) +
  geom_bar( stat="identity") +
  CTCN_tint('mixed7') + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) 

p


```


```{r QCViolin}

p <- VlnPlot(clusters, features = 'nFeature_RNA', pt.size = 0) + NoLegend() + ggtitle('Number of Unique Genes') + xlab('ClusterID') + CTCN_tint('mixed7')
p1 <- VlnPlot(clusters, features = 'nCount_RNA', pt.size = 0) + NoLegend() +ggtitle('Number of Transcripts') + xlab('ClusterID') +CTCN_tint('mixed7')


p1/p

VlnPlot(clusters, features = 'nFeature_RNA',group.by = 'orig.ident', pt.size = 0) + NoLegend()
VlnPlot(clusters, features = 'nCount_RNA', pt.size = 0) + NoLegend()
```

```{r HeatMap}
library(dplyr)
clusters <- readRDS(file = '/Users/sanachintamen/Desktop/Cx3cr1_clusters.Rds', refhook = NULL)
DefaultAssay(clusters) <- 'RNA'

clusters <- NormalizeData(clusters)
clusters <- FindVariableFeatures(clusters)
all.genes <- rownames(clusters)
clusters <- ScaleData(clusters, features = all.genes)

DGE <- FindAllMarkers(clusters, logfc.threshold = 0.25, min.pct = 0.7, only.pos = TRUE, assay = 'RNA')

top_markers <- DGE %>% group_by(cluster) %>% top_n(n = 4, wt = avg_log2FC)
genelist <- unique(top_markers$gene)
DoHeatmap(subset(clusters, downsample =30), features = genelist, group.colors = c("#f38ff0","#ffbb91","#c18ab6","#01CACA","#ffafbd","#ff5e62","#e8ffc1","#cccc00","#70e1f5","#9599e8","#aa4371","#065c6f","#edc988","#ff8b3d")) + NoLegend()

p2f + CTCN_chroma('mixed7')
```

```{r Featureplots}
library(Seurat)
library(patchwork)
library(ggplot2)
clusters <- readRDS(file = '/Users/sanachintamen/Desktop/Cx3cr1_clusters.Rds', refhook = NULL)

DefaultAssay(clusters) <- 'RNA'
clusters <- NormalizeData(clusters)
clusters <- FindVariableFeatures(clusters)
all.genes <- rownames(clusters)
clusters <- ScaleData(clusters, features = all.genes)



scheme <- c("#d5d0bc", "#ff5e62")


#####
# canonical markers
p1 <- FeaturePlot(clusters, features = 'Tmem119', cols = scheme)+ 
  theme_void() + ggtitle('Tmem119' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))

p2 <- FeaturePlot(clusters, features = 'Aif1',cols = scheme) + 
  theme_void() + ggtitle('Aif1' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))

p3 <-FeaturePlot(clusters, features = 'Cd68',cols = scheme)+
  theme_void() + ggtitle('Cd68' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))

p4 <- FeaturePlot(clusters, features = 'Xist', cols = scheme)+ 
  theme_void() + ggtitle('Xist' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))

p1 / p2 / p3 / p4

# State specific signature


p5 <- FeaturePlot(clusters, features = 'Apoe',cols = scheme)+
  theme_void() + ggtitle('Apoe' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))

p6 <- FeaturePlot(clusters, features = 'Axl',cols = scheme)+ 
  theme_void() + ggtitle('Axl' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))

p7 <- FeaturePlot(clusters, features = 'Egr1', cols = scheme)+
  theme_void() + ggtitle('Egr1' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))

p8 <- FeaturePlot(clusters, features = 'Rtp4', cols =scheme)+
  theme_void() + ggtitle('Rtp4' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))

 p5 /p6 /p7 /p8


#
p9 <- FeaturePlot(clusters, features = 'Mki67', cols = scheme)+ 
  theme_void() + ggtitle('Mki67' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))


p10 <- FeaturePlot(clusters, features = 'Ttr',cols = scheme)+
  theme_void() + ggtitle('Ttr' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))

p11 <- FeaturePlot(clusters, features = 'Pf4', cols = scheme)+ 
  theme_void() + ggtitle('Pf4' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))


p12 <- FeaturePlot(clusters, features = 'Cd74',cols = scheme)+ 
  theme_void() + ggtitle('Cd74' ) +
  theme(plot.title = element_text(hjust = 0.5, face = 'bold'))


p9/p10/p11/p12

```

```{r SGZmarkers}
library(dplyr)
library(Seurat)
library(ggplot2)
DefaultAssay(clusters) <- 'SCT'
cluster4_markers <- filter(markers_sct_scale, cluster == 4 )
cluster4_markers$gene


clusters <- readRDS(file = '/Users/sanachintamen/Desktop/Cx3cr1_clusters.Rds', refhook = NULL)
DefaultAssay(clusters) <- 'RNA'
clusters <- NormalizeData(clusters)
clusters <- FindVariableFeatures(clusters)
all.genes <- rownames(clusters)
clusters <- ScaleData(clusters, features = all.genes)

DotPlot(clusters, features =cluster4_markers$gene, cols = 'Spectral')+ RotatedAxis() + labs(y="Cluster ID", x = "Gene")



SGZvsMG <- FindMarkers(clusters, ident.1 = 4, ident.2 = c(0,1), logfc.threshold = 0.25)
SGZ <- FindMarkers(clusters, ident.1 = 4, logfc.threshold = 0.25)


#butovsky 2014
MG_markers <- c('Fcrls', 'Tmem119', 'Olfml3', 'Hexb', 'Tgfbr1', 'Gpr34', 'Sall1', 'Mertk', 'Pros1', 'Gas6', 'Aif1', 'Csf1r','C1qc')
p0 <- VlnPlot(clusters, features = MG_markers, idents = c(0,1,4), pt.size = 0)
RidgePlot(clusters, features = MG_markers, idents = c(0,1,4))


ggsave(
  '/Users/sanachintamen/Desktop/MGup.jpeg',
  plot = p0,
  device = 'jpeg',
  width = 280,
  height = 200,
  units = 'mm',
  dpi = 300
)

dot <- DotPlot(clusters, features = MG_markers, cols = c('Spectral'))

top_SGZ <- DGE %>% group_by(cluster) %>% top_n(n = 4, wt = avg_log2FC)

top_SGZ <- top_n(SGZvsMG, n = 20, wt= avg_log2FC)
rownames(top_SGZ)


top_SGZ <- 
DotPlot(clusters, features = rownames(top_SGZ), cols = 'Spectral')+ RotatedAxis() + labs(y="Cluster ID", x = "Gene")
DotPlot(clusters, features = rownames(top_SGZ), idents = c(0,1,4), cols = 'Spectral')+ RotatedAxis() + labs(y="Cluster ID", x = "Gene")

VlnPlot(clusters, features =rownames(top_SGZ), idents = c(0,1,4), pt.size = 0)

RidgePlot(clusters, features =rownames(top_SGZ), idents = c(0,1,4))

VlnPlot(clusters, features = 'Cd68', split.by = 'orig.ident', pt.size = 0)
p1 <- VlnPlot(clusters, features = 'Cd68', pt.size = 0, log = TRUE) + CTCN_tint('mixed7') + NoLegend()
p0 <- RidgePlot(clusters, features = 'Cd68') + CTCN_tint('mixed7')
DotPlot(clusters, features = 'Cd68', split.by = 'orig.ident', cols = 'Spectral')

```

```{r VolcanoPlot}
library(ggrepel)
library(EnhancedVolcano)



SGZvsMG <- FindMarkers(clusters, ident.1 = 4, ident.2 = c(0,1), logfc.threshold = 0.25)
SGZ <- FindMarkers(clusters, ident.1 = 4, logfc.threshold = 0.25)

p1 <- EnhancedVolcano(SGZvsMG,
    lab = rownames(SGZvsMG),
    x = 'avg_log2FC',
    y = 'p_val_adj',
    xlim = c(-1.5,3),
    pCutoff = 10e-32,
    FCcutoff = 0.5,
    pointSize = 2.0,
    labSize = 6.0,
    colAlpha = 1,
    gridlines.major = T,
    gridlines.minor = T,
    drawConnectors = T,
    widthConnectors = 0.1,
    boxedLabels = F,
    legendLabels=c('n.s.','Log2FC','adj p-val',
      'adj p-val + log2FC'),
    legendPosition = 'bottom',
    legendLabSize = 12,
    legendIconSize = 2.0,
    title = NULL,
    subtitle = NULL)

p1 
p2 <- EnhancedVolcano(SGZ,
    lab = rownames(SGZ),
    x = 'avg_log2FC',
    y = 'p_val_adj',
    pCutoff = 10e-32,
    FCcutoff = 0.5,
    pointSize = 3.0,
    labSize = 6.0,
    colAlpha = 1,
    legendLabels=c('Not sig.','Log (base 2) FC','p-value',
      'p-value & Log (base 2) FC'),
    legendPosition = 'right',
    legendLabSize = 16,
    legendIconSize = 5.0)
pdf(file = "/Users/sanachintamen/Desktop/SGZ_volcanoplot.pdf",   # The directory you want to save the file in
    width = 10, # The width of the plot in inches
    height = 14) # The height of the plot in inches

 EnhancedVolcano(SGZ,
    lab = rownames(SGZ),
    x = 'avg_log2FC',
    y = 'p_val_adj',
    pCutoff = 10e-32,
    FCcutoff = 0.5,
    pointSize = 1.0,
    labCol = 'black',
    labFace = 'bold',
    boxedLabels = TRUE,
    colAlpha = 4/5,
    legendPosition = 'right',
    legendLabSize = 12,
    legendIconSize = 8.0,
    drawConnectors = TRUE,
    widthConnectors = 1.0,
    colConnectors = 'black')
 
 dev.off()
 
write.csv(SGZ, file = '/Users/sanachintamen/Desktop/SGZ_DGE.csv')
 
```

```{r Dendrogram}
library(ggplot2)
library(ggdendro)
library(reshape2)
DefaultAssay(clusters) <- 'integrated'
MG_tree <- BuildClusterTree(clusters)

ggdendrogram(MG_tree)

PlotClusterTree(MG_tree, reorder = T )
p <- plot(MG_tree, type = 'phylogram')

hclust(MG_tree)

plot(MG_tree, xlim = c(1, 20), ylim = c(1,8))

hcd <- as.dendrogram(MG_tree)

cols <- c("#a9a9a9", "#1f77b4", "#ff7f0e", "#2ca02c")

hclust(clusters)

p <- plot_ggdendro(clusters,
                   direction   = "tb",
                   scale.color = cols,
                   label.size  = 2.5,
                   branch.size = 0.5,
                   expand.y    = 0.2)

p <- p + theme_void() + expand_limits(x = c(-1, 32))
p
```









## Gene ontology

For visualization click [here](http://yulab-smu.top/clusterProfiler-book/chapter12.html)

```{r topGO}
library(Seurat)
library(topGO)
library("org.Mm.eg.db")
library(genefilter)
library(dplyr)
library(tidyr)
library(tidyselect)
library(ggplot2)
library(enrichplot)

clusters <- readRDS(file = '/Users/sanachintamen/Desktop/Cx3cr1_clusters.Rds', refhook = NULL)
DefaultAssay(clusters) <- 'RNA'
clusters <- NormalizeData(clusters)
clusters <- FindVariableFeatures(clusters)
all.genes <- rownames(clusters)
clusters <- ScaleData(clusters, features = all.genes)

SGZvsMG <- FindMarkers(clusters, ident.1 = 4, ident.2 = c(0,1), logfc.threshold = 0.25)
gene <- rownames(SGZvsMG)
SGZvsMG <- cbind(gene, SGZvsMG)
SGZvsMG <- as_data_frame(SGZvsMG)
write.csv(SGZvsMG, file = '/Users/sanachintamen/Desktop/SGZvsMG.csv')

topDiffGenes <- function (genelist) 
{
  return(genelist < 0.01)
}


UpGenes <- function (genelist) 
{
  genes_up <- filter(genelist, avg_log2FC > 0)
  gene <- genes_up$gene
  genes_up <- as.numeric(genes_up$p_val_adj)
  names(genes_up) <- gene
  rm(gene)
  return(genes_up)
}


DownGenes <- function (genelist) 
{
  genes_down <- filter(genelist, avg_log2FC < 0)
  gene <- genes_down$gene
  genes_down <- as.numeric(genes_down$p_val_adj)
  names(genes_down) <- gene
  rm(gene)
  return(genes_down)
}



up <- UpGenes(SGZvsMG)
down <- DownGenes(SGZvsMG)


annotation <- function(genelist)
{
GOdata <- new("topGOdata",
              description = 'test run', ontology = "BP",
              allGenes = genelist, geneSel = topDiffGenes,
              annot = annFUN.org,
              nodeSize = 10,
              mapping = 'org.Mm.eg.db',
              ID = 'symbol')
resultFisher <- runTest(GOdata, 
                        algorithm = "classic", 
                        statistic = "fisher")
resultKS <- runTest(GOdata, 
                    algorithm = "classic", 
                    statistic = "ks")
resultKS.elim <- runTest(GOdata, 
                         algorithm = "elim", 
                         statistic = "ks")
allRes <- GenTable(GOdata, classicFisher = resultFisher,
                           classicKS = resultKS, 
                           elimKS = resultKS.elim,
                           orderBy = "elimKS", 
                          ranksOf = "classicFisher", 
                          topNodes = 200,
                          numChar = 200)  
return(allRes)
}

downGO <- annotation(down)

upGO <- annotation(up)


```


```{r plotGO}
neuronup <- allRes[c(11,23,43,56,57,86,95,92,107,122,129,134,151,177,178),]
neurondown <- downGO[c(4,5,6,7,8,10,13,14,27,39,42,53,59,74,98),]

neuronup <- as_data_frame(neuronup)
neuronup <- neuronup %>% arrange(desc(Annotated))

relevel(neuronup, neuronup$Annotated)

#enrichment_barplot(object, result, showTerms = 10, numChar = 40, 
		   #orderBy = "Scores", y = "Count", 
		   #xlab = NULL, ylab = NULL, title = NULL)


  
 
 
p0 <- ggplot(neuronup, aes(Annotated, Term)) +
  geom_col(fill = 'firebrick') +
  scale_y_discrete(position = 'right') 
  
    


p1 <- ggplot(neurondown, aes(Annotated, Term)) +
  geom_col(fill = 'blue') +
  xlim(50,0)


p0 + p1
    
    aes(x = Term, y = Annotated, fill = classicKS)) + 
  coord_flip()
  
  
reds <- c('#800000','#880808','#8B0000','#8D021F','#B22222','#660000','#990000','#960018','C21807', '#CC0000','#DC143C','#FF0000','#FF3333','#FF4500')
  scale_fill_manual(values= c('red', 'red1', 'red2', 'red3', 'red4', 'rosybrown', 'firebrick1', 'firebrick2', 'firebrick3', 'firebrick4', 'tomato', 'tomato1', 'tomato2'))+
  coord_flip() 



```


```{r}

library(Seurat)
library(ggplot2)
require(ggdendro)
require(Rmisc)
library(Matrix)
library(MASS)
library(xtable)
library(Matrix.utils)
library(DOSE)
library(reshape2)

DefaultAssay(clusters) <- 'integrated'

MG_tree <- BuildClusterTree(clusters, reorder = TRUE, reorder.numeric = TRUE)

#can use same parameteres as plot.phylo {ape}
PlotClusterTree(MG_tree) +RotatedAxis()
                
                use.edge.length = TRUE,
    node.pos = NULL, show.tip.label = TRUE, show.node.label = FALSE,
    edge.color = "black", edge.width = 1, edge.lty = 1, font = 3,
    cex = par("cex"), adj = NULL, srt = 0, no.margin = FALSE,
    root.edge = FALSE, label.offset = 0, underscore = FALSE,
    x.lim = NULL, y.lim = NULL, direction = "rightwards",
    lab4ut = NULL, tip.color = "black", plot = TRUE,
    rotate.tree = 0, open.angle = 0, node.depth = 1,
    align.tip.label = FALSE)



UMAPPlot(MG_tree, label = TRUE)

MG_tree <- BuildClusterTree(clusters, reorder = TRUE, reorder.numeric = TRUE)


                            use.edge.length = TRUE,
    node.pos = NULL, show.tip.label = TRUE, show.node.label = FALSE,
    edge.color = "black", edge.width = 1, edge.lty = 1, font = 3,
    cex = par("cex"), adj = NULL, srt = 0, no.margin = FALSE,
    root.edge = FALSE, label.offset = 0, underscore = FALSE,
    x.lim = NULL, y.lim = NULL, direction = "rightwards",
    lab4ut = NULL, tip.color = "black", plot = TRUE,
    rotate.tree = 0, open.angle = 0, node.depth = 1,
    align.tip.label = FALSE)

```

