---
title: "SGZ_cluster"
output: github_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r Data}
library(Seurat)
clusters <- readRDS(file = '/Users/sanachintamen/Desktop/Cx3cr1_clusters.Rds', refhook = NULL)
DefaultAssay(clusters) <- 'RNA'
clusters <- NormalizeData(clusters)
clusters <- FindVariableFeatures(clusters)
all.genes <- rownames(clusters)
clusters <- ScaleData(clusters, features = all.genes)
```




```{r SGZmarkers}
library(dplyr)
library(Seurat)
library(ggplot2)

#  "#f38ff0","#ffbb91","#ffafbd"


SGZvsMG <- FindMarkers(clusters, ident.1 = 4, ident.2 = c(0,1), logfc.threshold = 0.25)


DotPlot(clusters, features = c('Trem2', 'Axl', 'Cst7', 'Ctsl', 'Lpl', 'Cd9', 'Csf1', 'Ccl6', 'Itgax', 'Lilrb4', 'Timp2'), cols = 'Spectral') + RotatedAxis() + labs(y="Cluster ID", x = "Gene") + ggtitle('DAM stage 2 genes')

#butovsky 2014
MG_markers <- c('Tmem119', 'P2ry12','Fcrls',  'Olfml3', 'Hexb', 'Tgfbr1', 'Gpr34', 'Sall1', 'Mertk', 'P2ry13', 'Csf1r', 'Gas6','C1qa', 'C1qb','Cd34')

MG_up <- c('Cd9', 'Cd63', 'Ftl1', 'Ctsz', 'Ctsb','Ctsd', 'Mif', 'C3ar1', 'C5ar1', 'Apoe', 'Mt1', 'Lyz2', 'Cd83','Lpl', 'Csf1' )
p0 <- VlnPlot(clusters, features = MG_markers, idents = c(0,1,4), pt.size = 0, ncol = 5, cols = c('dodgerblue4','seagreen4', 'tomato4'))
p1 <- VlnPlot(clusters, features = MG_up, idents = c(0,1,4), pt.size = 0, ncol = 5,cols = c('dodgerblue4','seagreen4', 'tomato4'))

p0/p1
p0

VlnPlot(clusters, features = 'Ctss', pt.size = 0)
RidgePlot(clusters, features = MG_markers, idents = c(0,1,4))

VlnPlot(clusters, features = 'Ctss', pt.size = 0)

ggsave(
  '/Users/sanachintamen/Desktop/MGmarkers.jpeg',
  plot = p0,
  device = 'jpeg',
  width = 6,
  units = 'in',
  dpi = 300
)

dot <- DotPlot(clusters, features = MG_markers, cols = c('Spectral'))

top_SGZ <- DGE %>% group_by(cluster) %>% top_n(n = 4, wt = avg_log2FC)

top_SGZ <- top_n(SGZvsMG, n = 20, wt= avg_log2FC)
rownames(top_SGZ)


top_SGZ <- 
DotPlot(clusters, features = rownames(top_SGZ), cols = 'Spectral')+ RotatedAxis() + labs(y="Cluster ID", x = "Gene")
DotPlot(clusters, features = rownames(top_SGZ), idents = c(0,1,4), cols = 'Spectral')+ RotatedAxis() + labs(y="Cluster ID", x = "Gene")

VlnPlot(clusters, features =rownames(top_SGZ), idents = c(0,1,4), pt.size = 0)

RidgePlot(clusters, features =rownames(top_SGZ), idents = c(0,1,4))

VlnPlot(clusters, features = 'Cd68', split.by = 'orig.ident', pt.size = 0)
p1 <- VlnPlot(clusters, features = 'Cd68', pt.size = 0, log = TRUE) + CTCN_tint('mixed7') + NoLegend()
p0 <- RidgePlot(clusters, features = 'Cd68') + CTCN_tint('mixed7')
DotPlot(clusters, features = 'Cd68', split.by = 'orig.ident', cols = 'Spectral')

```

```{r VolcanoPlot}
library(ggrepel)
library(EnhancedVolcano)
#Note: run code in SGZ chunk first to get gene list

p1 <- EnhancedVolcano(SGZvsMG,
    lab = rownames(SGZvsMG),
    x = 'avg_log2FC',
    y = 'p_val_adj',
    xlim = c(-1,3),
    pCutoff = 10e-32,
    FCcutoff = 0.5,
    pointSize = 1.0,
    labSize = 6.0,
    colAlpha = 1,
    gridlines.major = T,
    gridlines.minor = T,
    drawConnectors = T,
    widthConnectors = 0.1,
    arrowheads = FALSE,
    lengthConnectors = 1,
    boxedLabels = F,
    legendLabels=c('n.s.','Log2FC','adj p-val',
      'adj p-val + log2FC'),
    legendPosition = 'bottom',
    legendLabSize = 12,
    legendIconSize = 2.0,
    title = NULL,
    subtitle = NULL)
p1+ geom_text_repel()
p1  + coord_flip()
p2 <- EnhancedVolcano(SGZ,
    lab = rownames(SGZ),
    x = 'avg_log2FC',
    y = 'p_val_adj',
    pCutoff = 10e-32,
    FCcutoff = 0.5,
    pointSize = 3.0,
    labSize = 6.0,
    colAlpha = 1,
    legendLabels=c('Not sig.','Log (base 2) FC','p-value',
      'p-value & Log (base 2) FC'),
    legendPosition = 'right',
    legendLabSize = 16,
    legendIconSize = 5.0)
pdf(file = "/Users/sanachintamen/Desktop/SGZ_volcanoplot.pdf",   # The directory you want to save the file in
    width = 8, # The width of the plot in inches
    height = 14) # The height of the plot in inches

 
 dev.off()
 
write.csv(SGZ, file = '/Users/sanachintamen/Desktop/SGZ_DGE.csv')
 
```

```{r topGO}
library(Seurat)
library(topGO)
library("org.Mm.eg.db")
library(genefilter)
library(dplyr)
library(tidyr)
library(tidyselect)
library(ggplot2)
library(enrichplot)


SGZvsMG <- FindMarkers(clusters, ident.1 = 4,ident.2 = c(0,1), logfc.threshold = 0.25)

SGZ <- FindMarkers(clusters, ident.1 = 4, logfc.threshold = 0.25)
gene <- rownames(SGZ)
SGZ <- cbind(gene, SGZ)
SGZ<- as_data_frame(SGZ)
up <- UpGenes(SGZ)
upGO_SGZ <- annotation(up,500)

#run code chunk first
gene <- rownames(SGZvsMG)
SGZvsMG <- cbind(gene, SGZvsMG)
SGZvsMG <- as_data_frame(SGZvsMG)
#write.csv(SGZvsMG, file = '/Users/sanachintamen/Desktop/SGZvsMG.csv')


up <- UpGenes(SGZvsMG)
down <- DownGenes(SGZvsMG)
downGO <- annotation(down)
upGO <- annotation(up, 500)
names(up)

edo <- enrichDGN(names(up))
barplot()
enrichplot::barplot


```

```{r}
library(DOSE)
data(geneList)
de <- names(geneList)[abs(geneList) > 2]
edo <- enrichDGN(de)
data1 <-read.delim("Combined GO.txt", header = TRUE, sep = "\t")                 
library(enrichplot)
barplot(edo, showCategory=30)
```
```{r}
# import package
library("ggplot2")

# create fake data
set.seed(1024) # keep reproducibility
go <- paste0("GO", sample(1000:2000, 5))
data <- data.frame("GOs" = rep(go, 2), 
                   "Condition" = rep(c("A", "B"), each = 5),
                   "GeneRatio" = 1 / sample(10, 10), 
                   "p.adjust" = 0.05 / sample(10, 10))

cc <- scales::seq_gradient_pal("blue", "red", "Lab")(seq(0,1,length.out=20))

# plot: dot plot
ggplot(data = data, aes(x = Condition, y = GOs, 
                        color = `p.adjust`, size = GeneRatio)) + 
  geom_point() +
  scale_color_gradient(low = "red", high = "blue") +
  theme_bw() + 
  ylab("") + 
  xlab("") + 
  ggtitle("GO enrichment analysis")



ggplot(data = neuronup, aes(x = Annotated, y = Term, 
                        color = elimKS, size = Significant)) + 
  geom_point() +
  scale_colour_manual(values=cc) +
  theme_bw() + 
  ylab("") + 
  xlab("") + 
  ggtitle("GO enrichment analysis")

ggplot(neuronup, aes(Term, color= elimKS)) +
  geom_bar() +
   scale_colour_manual(values=cc) 
```




```{r plotGO, echo = FALSE}
neuronup <- upGO[c(11,23,43,56,57,86,95,92,107,122,129,134,143,151,177,178, 123,69),]
neurondown <- downGO[c(4,5,6,7,8,10,13,14,27,39,42,53,59,74,98),]

neuronup <- as_data_frame(neuronup)
neuronup <- neuronup %>% arrange(desc(Annotated))

relevel(neuronup, neuronup$Annotated)

#enrichment_barplot(object, result, showTerms = 10, numChar = 40, 
		   #orderBy = "Scores", y = "Count", 
		   #xlab = NULL, ylab = NULL, title = NULL)


filtered <- filter(upGO, elimKS < 0.05)
 
 
p0 <- ggplot(neuronup, aes(Annotated, Term)) +
  geom_col(fill = 'firebrick') +
  scale_y_discrete(position = 'left') 
  
    
p0

p1 <- ggplot(neurondown, aes(Annotated, Term)) +
  geom_col(fill = 'blue') +
  xlim(50,0)


p0 + p1
    
p1 + p0  
  
reds <- c('#800000','#880808','#8B0000','#8D021F','#B22222','#660000','#990000','#960018','C21807', '#CC0000','#DC143C','#FF0000','#FF3333','#FF4500')
  scale_fill_manual(values= c('red', 'red1', 'red2', 'red3', 'red4', 'rosybrown', 'firebrick1', 'firebrick2', 'firebrick3', 'firebrick4', 'tomato', 'tomato1', 'tomato2'))+
  coord_flip() 



```